#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  5 18:34:07 2018

@author: soufiane
"""

import numpy as np

def total_count_normalization(count_data):
    
    return (1.*count_data.transpose() / np.sum(count_data,1)).transpose() * 10**6